import React, { useEffect, useState, useCallback } from "react";
import { useAppStore } from "../store/appStore";
import { enhancePost, generateHooks, type Tone } from "../utils/openai";
import { getStoredApiKey } from "../utils/storage";
import {
  IconSparkles,
  IconFishHook,
  IconSettings,
  IconRefresh,
  IconCopy,
  IconCheck,
  IconAlertTriangle,
  IconBrandLinkedin,
  IconLoader2,
} from "@tabler/icons-react";
import { toast, Toaster } from "sonner";

const TONES: { value: Tone; label: string }[] = [
  { value: "default", label: "Default" },
  { value: "excited", label: "Excited" },
  { value: "story", label: "Story" },
  { value: "professional", label: "Professional" },
  { value: "casual", label: "Casual" },
];

// Skeleton Loader Component
const Skeleton: React.FC<{ className?: string }> = ({ className = "" }) => (
  <div
    className={`bg-gradient-to-r from-neutral-200 via-neutral-100 to-neutral-200 bg-[length:200%_100%] animate-[shimmer_1.5s_infinite] rounded-lg ${className}`}
    style={{
      backgroundSize: "200% 100%",
      animation: "shimmer 1.5s infinite",
    }}
  />
);

const SidePanel: React.FC = () => {
  const {
    scrapedText,
    enhancedText,
    selectedTone,
    hooks,
    isGeneratingHooks,
    advancedInputs,
    advancedResult,
    activeTab,
    isEnhancing,
    sourceTabId,
    setScrapedText,
    setEnhancedText,
    setSelectedTone,
    setHooks,
    addHooks,
    setIsGeneratingHooks,
    setAdvancedInputs,
    setAdvancedResult,
    setActiveTab,
    setIsEnhancing,
    setError,
    setSourceTabId,
  } = useAppStore();

  const [hasApiKey, setHasApiKey] = useState<boolean>(true);
  const [copiedIndex, setCopiedIndex] = useState<number | null>(null);
  const [hasAutoEnhanced, setHasAutoEnhanced] = useState<boolean>(false);
  const [hasAutoGeneratedHooks, setHasAutoGeneratedHooks] =
    useState<boolean>(false);

  // Inject shimmer animation
  useEffect(() => {
    const style = document.createElement("style");
    style.textContent = `
      @keyframes shimmer {
        0% { background-position: 200% 0; }
        100% { background-position: -200% 0; }
      }
    `;
    document.head.appendChild(style);
    return () => style.remove();
  }, []);

  // Check for API key on mount
  useEffect(() => {
    getStoredApiKey().then((key) => setHasApiKey(!!key));
  }, []);

  // Get scraped text from background
  useEffect(() => {
    chrome.runtime.sendMessage({ type: "GET_SCRAPED_TEXT" }, (response) => {
      if (response?.text) setScrapedText(response.text);
      if (response?.tabId) setSourceTabId(response.tabId);
    });
  }, [setScrapedText, setSourceTabId]);

  // Auto-enhance on mount
  useEffect(() => {
    if (
      scrapedText &&
      !enhancedText &&
      !hasAutoEnhanced &&
      !isEnhancing &&
      hasApiKey &&
      activeTab === "enhance"
    ) {
      setHasAutoEnhanced(true);
      handleEnhance();
    }
  }, [
    scrapedText,
    enhancedText,
    hasAutoEnhanced,
    isEnhancing,
    hasApiKey,
    activeTab,
  ]);

  // Auto-generate hooks
  useEffect(() => {
    if (
      activeTab === "hooks" &&
      scrapedText &&
      hooks.length === 0 &&
      !hasAutoGeneratedHooks &&
      !isGeneratingHooks &&
      hasApiKey
    ) {
      setHasAutoGeneratedHooks(true);
      handleGenerateHooks();
    }
  }, [
    activeTab,
    scrapedText,
    hooks.length,
    hasAutoGeneratedHooks,
    isGeneratingHooks,
    hasApiKey,
  ]);

  const handleEnhance = useCallback(async () => {
    if (!scrapedText) {
      toast.error("No source text available");
      return;
    }

    setIsEnhancing(true);
    setError(null);

    try {
      const result = await enhancePost(scrapedText, { tone: selectedTone });
      setEnhancedText(result);
      toast.success("Post enhanced!");
    } catch (err) {
      const message = err instanceof Error ? err.message : "Enhancement failed";
      setError(message);
      toast.error(message);
    } finally {
      setIsEnhancing(false);
    }
  }, [scrapedText, selectedTone, setEnhancedText, setError, setIsEnhancing]);

  const handleToneChange = useCallback(
    async (tone: Tone) => {
      setSelectedTone(tone);
      if (scrapedText && hasApiKey) {
        setIsEnhancing(true);
        try {
          const result = await enhancePost(scrapedText, { tone });
          setEnhancedText(result);
          toast.success("Regenerated with new tone!");
        } catch (err) {
          const message =
            err instanceof Error ? err.message : "Enhancement failed";
          toast.error(message);
        } finally {
          setIsEnhancing(false);
        }
      }
    },
    [scrapedText, hasApiKey, setSelectedTone, setEnhancedText, setIsEnhancing],
  );

  const handleGenerateHooks = useCallback(async () => {
    if (!scrapedText) {
      toast.error("No source text available");
      return;
    }

    setIsGeneratingHooks(true);

    try {
      const newHooks = await generateHooks(scrapedText);
      if (hooks.length === 0) {
        setHooks(newHooks);
      } else {
        addHooks(newHooks);
      }
      toast.success("Hooks generated!");
    } catch (err) {
      const message =
        err instanceof Error ? err.message : "Failed to generate hooks";
      toast.error(message);
    } finally {
      setIsGeneratingHooks(false);
    }
  }, [scrapedText, hooks.length, setHooks, addHooks, setIsGeneratingHooks]);

  const handleCopyHook = useCallback(
    async (hookText: string, index: number) => {
      try {
        await navigator.clipboard.writeText(hookText);
        setCopiedIndex(index);
        toast.success("Copied!");
        setTimeout(() => setCopiedIndex(null), 2000);
      } catch {
        toast.error("Failed to copy");
      }
    },
    [],
  );

  const handleGenerateAdvanced = useCallback(async () => {
    const { whoAreYou, motive, context } = advancedInputs;

    if (!whoAreYou.trim() || !motive.trim() || !context.trim()) {
      toast.error("Please fill all fields");
      return;
    }

    if (!scrapedText) {
      toast.error("No source text available");
      return;
    }

    setIsEnhancing(true);

    try {
      const result = await enhancePost(scrapedText, {
        role: whoAreYou,
        motive,
        context,
      });
      setAdvancedResult(result);
      toast.success("Advanced post generated!");
    } catch (err) {
      const message = err instanceof Error ? err.message : "Generation failed";
      toast.error(message);
    } finally {
      setIsEnhancing(false);
    }
  }, [advancedInputs, scrapedText, setAdvancedResult, setIsEnhancing]);

  const handleInsert = useCallback(() => {
    let textToInsert = "";

    if (activeTab === "enhance") {
      textToInsert = enhancedText;
    } else if (activeTab === "advanced") {
      textToInsert = advancedResult;
    }

    if (!textToInsert) {
      toast.error("Nothing to insert");
      return;
    }

    if (sourceTabId) {
      chrome.runtime.sendMessage(
        {
          type: "INSERT_TEXT_TO_LINKEDIN",
          tabId: sourceTabId,
          text: textToInsert,
        },
        (response) => {
          if (response?.success) {
            toast.success("Inserted into LinkedIn!");
            window.close();
          } else {
            navigator.clipboard.writeText(textToInsert).then(() => {
              toast.success("Copied! Paste into LinkedIn.");
            });
          }
        },
      );
    } else {
      navigator.clipboard.writeText(textToInsert).then(() => {
        toast.success("Copied! Paste into LinkedIn.");
      });
    }
  }, [activeTab, enhancedText, advancedResult, sourceTabId]);

  const tabs = [
    { id: "enhance" as const, label: "Enhance", icon: IconSparkles },
    { id: "hooks" as const, label: "Hooks", icon: IconFishHook },
    { id: "advanced" as const, label: "Advanced", icon: IconSettings },
  ];

  // Check if Insert button should show (not for Hooks tab)
  const showInsertButton = activeTab !== "hooks";

  return (
    <div className="min-h-screen flex flex-col">
      <Toaster
        position="top-center"
        toastOptions={{
          style: {
            background: "#171717",
            color: "#fafafa",
            border: "1px solid #404040",
            fontSize: "13px",
          },
          duration: 3000,
        }}
      />

      {/* Header */}
      <header className="bg-white border-b border-[#d4d2cf] px-4 py-4">
        <h1 className="text-lg font-semibold text-black">
          LinkedIn Post Enhancer
        </h1>
      </header>

      {/* API Key Warning */}
      {!hasApiKey && (
        <div className="bg-red-50 border-b border-red-200 px-4 py-3 flex items-center gap-2">
          <IconAlertTriangle className="w-4 h-4 text-red-800 shrink-0" />
          <span className="text-sm text-red-800">
            No API key found. Configure in extension popup.
          </span>
        </div>
      )}

      {/* Tab Navigation */}
      <div className="bg-white border-b border-[#d4d2cf] flex">
        {tabs.map((tab) => {
          const Icon = tab.icon;
          const isActive = activeTab === tab.id;
          return (
            <button
              key={tab.id}
              onClick={() => setActiveTab(tab.id)}
              className={`flex-1 py-3 px-4 text-sm font-medium flex items-center justify-center gap-2 transition-colors ${
                isActive
                  ? "text-black border-b-2 border-black"
                  : "text-[#666666] hover:text-black"
              }`}
            >
              <Icon className="w-4 h-4" />
              <span>{tab.label}</span>
            </button>
          );
        })}
      </div>

      {/* Content Area */}
      <div
        className={`flex-1 overflow-y-auto p-4 ${showInsertButton ? "pb-24" : "pb-4"}`}
      >
        {activeTab === "enhance" && (
          <EnhanceTab
            enhancedText={enhancedText}
            selectedTone={selectedTone}
            scrapedText={scrapedText}
            isEnhancing={isEnhancing}
            onToneChange={handleToneChange}
            onRegenerate={handleEnhance}
            onSourceTextChange={setScrapedText}
          />
        )}

        {activeTab === "hooks" && (
          <HooksTab
            hooks={hooks}
            isGenerating={isGeneratingHooks}
            copiedIndex={copiedIndex}
            onCopy={handleCopyHook}
            onGenerateMore={handleGenerateHooks}
          />
        )}

        {activeTab === "advanced" && (
          <AdvancedTab
            advancedInputs={advancedInputs}
            advancedResult={advancedResult}
            isEnhancing={isEnhancing}
            onInputChange={setAdvancedInputs}
            onGenerate={handleGenerateAdvanced}
          />
        )}
      </div>

      {/* Fixed Footer - Only for Enhance & Advanced tabs */}
      {showInsertButton && (
        <footer className="fixed bottom-0 left-0 right-0 bg-white border-t border-[#d4d2cf] px-5 py-2 shadow-[0_-2px_8px_rgba(0,0,0,0.06)]">
          <button
            onClick={handleInsert}
            className="w-full py-2.5 px-4 bg-neutral-900 text-white rounded-lg text-base font-semibold tracking-wide hover:bg-neutral-800 transition-colors flex items-center justify-center gap-2"
          >
            <IconBrandLinkedin className="w-5 h-5" />
            <span>Insert into LinkedIn</span>
          </button>
        </footer>
      )}
    </div>
  );
};

// Enhance Tab
interface EnhanceTabProps {
  enhancedText: string;
  selectedTone: Tone;
  scrapedText: string;
  isEnhancing: boolean;
  onToneChange: (tone: Tone) => void;
  onRegenerate: () => void;
  onSourceTextChange: (text: string) => void;
}

const EnhanceTab: React.FC<EnhanceTabProps> = ({
  enhancedText,
  selectedTone,
  scrapedText,
  isEnhancing,
  onToneChange,
  onRegenerate,
  onSourceTextChange,
}) => (
  <div className="space-y-4">
    {/* Enhanced Version */}
    <div>
      <div className="flex items-center justify-between mb-2">
        <label className="text-sm font-medium text-black">
          Enhanced Version
        </label>
        <button
          onClick={onRegenerate}
          disabled={isEnhancing}
          className="text-sm text-[#666666] hover:text-black flex items-center gap-1 disabled:opacity-50 transition-colors"
        >
          {isEnhancing ? (
            <IconLoader2 className="w-4 h-4 animate-spin" />
          ) : (
            <IconRefresh className="w-4 h-4" />
          )}
          <span>Regenerate</span>
        </button>
      </div>
      {isEnhancing && !enhancedText ? (
        <Skeleton className="w-full h-32" />
      ) : (
        <textarea
          readOnly
          value={enhancedText}
          placeholder="Enhanced version will appear here..."
          className="w-full h-32 p-3 bg-white border border-[#d4d2cf] rounded-lg text-sm text-black placeholder:text-[#999999] resize-none focus:outline-none focus:ring-2 focus:ring-[#0a66c2]/30 focus:border-[#0a66c2]"
        />
      )}
    </div>

    {/* Tone Selector */}
    <div>
      <label className="text-sm font-medium text-black block mb-2">Tone</label>
      <select
        value={selectedTone}
        onChange={(e) => onToneChange(e.target.value as Tone)}
        className="w-full p-2.5 bg-white border border-[#d4d2cf] rounded-lg text-sm text-black focus:outline-none focus:ring-2 focus:ring-[#0a66c2]/30 focus:border-[#0a66c2]"
      >
        {TONES.map((tone) => (
          <option key={tone.value} value={tone.value}>
            {tone.label}
          </option>
        ))}
      </select>
    </div>

    {/* Source Text */}
    <div>
      <label className="text-sm font-medium text-black block mb-2">
        Source Text
      </label>
      <textarea
        value={scrapedText}
        onChange={(e) => onSourceTextChange(e.target.value)}
        placeholder="Your original LinkedIn caption..."
        className="w-full h-24 p-3 bg-white border border-[#d4d2cf] rounded-lg text-sm text-black placeholder:text-[#999999] resize-none focus:outline-none focus:ring-2 focus:ring-[#0a66c2]/30 focus:border-[#0a66c2]"
      />
    </div>
  </div>
);

// Hooks Tab - NO Insert Button
interface HooksTabProps {
  hooks: string[];
  isGenerating: boolean;
  copiedIndex: number | null;
  onCopy: (text: string, index: number) => void;
  onGenerateMore: () => void;
}

const HooksTab: React.FC<HooksTabProps> = ({
  hooks,
  isGenerating,
  copiedIndex,
  onCopy,
  onGenerateMore,
}) => (
  <div className="space-y-4">
    <h2 className="text-sm font-medium text-black">Powerful Hooks</h2>

    {hooks.length === 0 && isGenerating ? (
      <div className="space-y-4">
        <Skeleton className="w-full h-16" />
        <Skeleton className="w-full h-16" />
        <Skeleton className="w-full h-16" />
      </div>
    ) : hooks.length > 0 ? (
      <div className="space-y-4">
        {hooks.map((hook, index) => (
          <div
            key={index}
            className="bg-white border border-[#d4d2cf] rounded-lg p-4 flex items-start justify-between gap-3 hover:border-[#0a66c2]/50 transition-colors"
          >
            <p className="text-sm text-black flex-1">{hook}</p>
            <button
              onClick={() => onCopy(hook, index)}
              className="text-[#666666] hover:text-[#0a66c2] shrink-0 transition-colors"
              title="Copy hook"
            >
              {copiedIndex === index ? (
                <IconCheck className="w-4 h-4 text-green-600" />
              ) : (
                <IconCopy className="w-4 h-4" />
              )}
            </button>
          </div>
        ))}
      </div>
    ) : (
      <div className="text-center py-8 text-[#666666] text-sm">
        <p>Click below to generate hooks</p>
      </div>
    )}

    <button
      onClick={onGenerateMore}
      disabled={isGenerating}
      className="w-full py-2.5 bg-neutral-900 text-white rounded-lg text-sm font-medium hover:bg-neutral-800 transition-colors disabled:opacity-50 flex items-center justify-center gap-2 mb-4"
    >
      {isGenerating ? (
        <>
          <IconLoader2 className="w-4 h-4 animate-spin" />
          <span>Generating...</span>
        </>
      ) : (
        <span>Generate 3 More Hooks</span>
      )}
    </button>
  </div>
);

// Advanced Tab
interface AdvancedTabProps {
  advancedInputs: { whoAreYou: string; motive: string; context: string };
  advancedResult: string;
  isEnhancing: boolean;
  onInputChange: (
    inputs: Partial<{ whoAreYou: string; motive: string; context: string }>,
  ) => void;
  onGenerate: () => void;
}

const AdvancedTab: React.FC<AdvancedTabProps> = ({
  advancedInputs,
  advancedResult,
  isEnhancing,
  onInputChange,
  onGenerate,
}) => (
  <div className="space-y-4">
    {/* Who are you */}
    <div>
      <label className="text-sm font-medium text-black block mb-2">
        Who are you?
      </label>
      <input
        type="text"
        value={advancedInputs.whoAreYou}
        onChange={(e) => onInputChange({ whoAreYou: e.target.value })}
        placeholder="e.g., SaaS founder, designer"
        className="w-full p-2.5 bg-white border border-[#d4d2cf] rounded-lg text-sm text-black placeholder:text-[#999999] focus:outline-none focus:ring-2 focus:ring-[#0a66c2]/30 focus:border-[#0a66c2]"
      />
    </div>

    {/* Motive */}
    <div>
      <label className="text-sm font-medium text-black block mb-2">
        What's your motive?
      </label>
      <input
        type="text"
        value={advancedInputs.motive}
        onChange={(e) => onInputChange({ motive: e.target.value })}
        placeholder="e.g., Share a product launch, teach a lesson"
        className="w-full p-2.5 bg-white border border-[#d4d2cf] rounded-lg text-sm text-black placeholder:text-[#999999] focus:outline-none focus:ring-2 focus:ring-[#0a66c2]/30 focus:border-[#0a66c2]"
      />
    </div>

    {/* Context */}
    <div>
      <label className="text-sm font-medium text-black block mb-2">
        Context (writing style)
      </label>
      <textarea
        value={advancedInputs.context}
        onChange={(e) => onInputChange({ context: e.target.value })}
        placeholder="e.g., Native Hindi style, professional but relatable"
        className="w-full h-20 p-3 bg-white border border-[#d4d2cf] rounded-lg text-sm text-black placeholder:text-[#999999] resize-none focus:outline-none focus:ring-2 focus:ring-[#0a66c2]/30 focus:border-[#0a66c2]"
      />
    </div>

    {/* Generate Button */}
    <button
      onClick={onGenerate}
      disabled={isEnhancing}
      className="w-full py-2.5 bg-neutral-900 text-white rounded-lg text-sm font-medium hover:bg-neutral-800 transition-colors disabled:opacity-50 flex items-center justify-center gap-2"
    >
      {isEnhancing ? (
        <>
          <IconLoader2 className="w-4 h-4 animate-spin" />
          <span>Generating...</span>
        </>
      ) : (
        <span>Generate Enhanced Post</span>
      )}
    </button>

    {/* Generated Result */}
    {isEnhancing && !advancedResult ? (
      <div>
        <label className="text-sm font-medium text-black block mb-2">
          Generated Post
        </label>
        <Skeleton className="w-full h-32" />
      </div>
    ) : advancedResult ? (
      <div>
        <label className="text-sm font-medium text-black block mb-2">
          Generated Post
        </label>
        <textarea
          readOnly
          value={advancedResult}
          className="w-full h-32 p-3 bg-white border border-[#d4d2cf] rounded-lg text-sm text-black resize-none"
        />
      </div>
    ) : null}
  </div>
);

export default SidePanel;
